apiVersion: v1
kind: Namespace
metadata:
  name: contour
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: contour
  namespace: contour
spec:
  interval: 10m0s
  url: https://projectcontour.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: contour
  namespace: contour
spec:
  chart:
    spec:
      chart: contour
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: contour
      version: 0.7.0
  interval: 10m0s
  values:
    envoy:
      resourcesPreset: large
      service:
        annotations:
          metallb.universe.tf/loadBalancerIPs: "169.229.226.81,2607:f140:8801::1:81"
        ipFamilyPolicy: PreferDualStack
    global:
      security:
        allowInsecureImages: true
