apiVersion: v1
kind: Secret
metadata:
    name: ocf-tsig
    namespace: cert-manager
stringData:
    key: ENC[AES256_GCM,data:oL6ZB8YFBEEds97KuqILU+Nija4O05r+2t6Hgqw+Yl9CxFUJpAwGIh9Ry/IBnPm5O8R2Dr0p0fjcZDYzxiw7YIA73+/YX6YF/Osa2XdwaPi6mFFo5yGJPA==,iv:8sMRbpcgJ+T4bVf9Abx4lqEGrHB6pXViHzZTTdvQsjY=,tag:dOIOX//FePiqnYgj2nixYA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDRQNGM2S3Iw
            R1VXYjJCUWhLTXp0NWZhSjA2bGlqQkVYTCtKMzREdGZjckV3ODJ3VDBoM1Z2WUtJ
            K2RPYlU4ZUJFYndrSlY5SmVJQXVnM1lBVWc0citxNDVQdEh3YkxhSXdwenBBOXo5
            b3FpVzlLTGNTbVpqTUdXVlpwdklMVVI5RnI0OTlPUnlQWTlXRlNhOWRPdDhacVd1
            RTlhWFdyRU5YNUlMUldVdndoeUE2Vk1HVjVQdVpNYmR1WkNWOHRFZDhTM3VoK0dQ
            WFd2TnBSOWxjME1yMEIrSUI3SkFyemY3bFd6alloSk1JMDBlbTlrNlU2dXVZVFNZ
            VjVzZ0dldmt6UmFBQVJsZUJBMUlQVm9QQW1PdmxnZjJ2VjFmSWhqVnlLNGh4ekZ1
            eTkyb3dnQ0lOVFhVb0R6amltdE1tSGlLOE1QYSt4VmxlZ1VaU0lWR0p4Qy9ZSnFF
            RFhVUWJDRWQ1T1ZaVHNOVWx1bEpjdUhCSXBXQ0xlTlBUVUpaWUt4SnZYRys1alM2
            RDcxME5jSWlIRnBxdEhRdWE1Y0kwSjM5R2oxY1psUXdNR092VG4xMFJuQ01CNThP
            K0VCbmVRTXN5UGFVelM1Ni9ydXYwS1M2R29ucktzWTRsbUtyQ2h6WHFvdVVvVkdh
            Yys5aFFLK0ZPdlMySXRRaFVGS1ljanMwdkRQd2FhSnp3KzRrejI5eGlRcnZIUDNt
            SkFhSUplVU0xald2a1lEcDRMcmtvd1Z2U1pUS2Yzby9WNVBNSEFwbmgralMyM2Fj
            emxwMDF1dDZnVkFqYTdhQTF6YVg4OXBsTWJDSmFvbUh5aHYvZm1oZTdZKzRwNktm
            MU1hSmJhQ2dPaitidks0SmN6THVpOU1sdVVKTXpDQmtHd2p5S1hzWVluVDBtZmJY
            Vld4UnQ3K2NuSnh6d1hUODFueHlRY3l1VGdJVHRWaDRHVVZoZncybHBDMHFYVXRV
            TXhLTTN6a0JFMUlUMEEzQVBURWYzUHVtMDZVcTJ2cnQwU2E5ck5BbDVkM1NRemlY
            MFRYOUNRcEJ6SkNFc0NkcXk1ZFBoaUJvTjZ6Q0FYL2xiRnJ4ZG5IdlV6ekI3c0NO
            N1hybUdqUUNkZ2ZGL01KTWpwekZDSU9DaEZrOExGcVZxUkpVZXV0VjBIVE1IbnNt
            bm5KKzBvaXBBd1BZZTdEUjVmbkFmTDE2YzVMa2paZ1g1ZDlvS2xldWYrT01sNWVy
            Y2k1amJMSEc5djR3alM0NTZYYTlpMnZyYlMzWlNuQmxmZ3Y0VGMrdW9FTHNtUXQv
            VElZL2tiY0xjN2dmNjVzYlVvRHV6a0k2dENzeENQZ0haVmhtbUNtaUd5ekxZTUxz
            NkRpVWl1QlZORSsrLzJjSFV0MlpTOUVRa3dJRnJCZExVNVVETVYvV3BlajhuOUVW
            MGxhYUw3VURuSzdyeFNSbEJrdkhPNFo2U3JxMTJzY3EzV0c0VDAzNENIOGMxUmpi
            RVd5bWRiNWN5YjArOHNJa2E4UVpMb1BVQ1k2Nzg3NFJWV1dhQXViaXVTYm5ZUGJH
            eWp0WUI3N0piYmVJMXVlN3BmOVdibzY3S3Y3bkRCNGt6TStRcWNuS3ZOdFVpcVcx
            Mkk0UWM4cEFKV3U1ZmlnaEt6Qi8rbG4xayttRElMdDRpVUZzNVd0c1Y5bXcvWTJP
            TXh1S3FZeDlUK3pCQU1xUkJYK3gzTVczeVI4NkIxVmNhWjVrZjlEYlVhUzFyeW5i
            aStzRGplaU0xZ2J4NFNMTnVSQkJ3RWhVK014eWdPMUV0UllzZFJzbjI1OXM4a2hy
            NlE4TGx2OHVqWFpZclMyMFkwT0gvVDNzbE1wb3J2VHhLWFZHTGVpQ3VTQnNyaFVX
            c3lENXJFZ3NmSTlIdWJRMVdhd0xzdDZaYW5HTS9GYmFSeXVjZU5pUWx3a1hvS3lV
            Y05ZbFpOOFJadkFETFhYTTZ5MjBieENlL2VSd0lYaWZhbXdWWWpoS09mRkRhZwpO
            Tm1scTFXdEhQY0k3Ylp0M2tnai9mVG12NDdGaHEyZ2ZLNkFiWWpoa0R3Ci0tLSBM
            WDZZYjRrak9iWG0xQXhVcVRjRUR4VTJ6SDIvMlM2OXlkMmJMWjg1azNzChZ1YWNk
            YNCFJ830Dq0YmegaZgmbwP9Z4oo0SyGk7m5ClN4TaT7jX9CA3ZBZkn8rw36aTq1V
            v9XEF8aqyWdB8/Q=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1g5ye2kphr9ajqclgu5rerkr3crcjp57j83uj2qtn7xzmg922ky59d99ej2w8qhygeszx3xcyfadexup3c86mqqdf72m8vyyxqfy23cppqpfhdgdjapwy5s4susq27msrv9z8h9x499235x4alurymfmryd6qk5hxjwqgdk9gng2vs9sxck7gwpm98pu07ny2sf4saempd8eypj8nd9kyek9pj6ygq9vh5ar2vf069snj55peyjq8ndmnzj2rtpkf27mzfr9qc75rqseghgpzhfn2uarcqymxyyt8p5m9netzygdhmw3wfws0nsvgk804xs4jwjw2gmxwgkfnfq6gk7cmsree8jkklqsjs9r475epaps540jukeadhp2hkxesxvrv2mm3x7uh4wvhjyn90xyc9tppcczk2urtewpdrvelx8pwuj6x4fmj48zpnnsvajw3pprcw4uc40gcz9p0hdur0pgf4yr46gpsy3nzdjrdxk4dwzzhkfncvy6fvsr99fndnqdlz6uwu6qzqlk9cnm35dqd88ttjqvjc3qnm6m8axvu4md7dtmjtf7m35fawr52hqd9y7lhkarcv3775tqhu8mjdg26wd54h9tm8dy65cxpa2z2pvzq24gyrtxq262yx8qh36z8qkcf385l00nagz9yxekty3qrx57z92f6sk7ejwysyu2f03ek5z9vh5sc5kfhdyc9c7ad66spw4ztvag3f08nylrptawg8m9p48enhwduzyje2j5ngrpgkm2pre9k20t5pv08qe5pvezu2zamvky6c6qjcg7jt2qyelp0zqa94cxmw2pfqvpcjej9wdy0hdqgqeceq0dt8yyyk2gnzcx2npxr5nuy4rthzfdyvx7k55espctr4lny844c3pxx4xyrwkqkzfnr9ljtf6axwk63e0xtqec4en5437l425epv03fud36d3nmjuptr9fx96msynry77fzuqmhqhpr4marqef4wfa0lqdknpkfhrrce7x98h9aerjky52uuvrysxa68rzfrufspvpvcvfkstq2z2ytnwm2zw8jsefmufd0qwftqvdqmqcxpuqa0sk3jcfvnd60gzjnqfz8v4prkajx0wd95ann4xs3nhy6qyay5e40gdl9n7fsme5ks7n3srluqm9jrzraue2la3vknav4qr609245zc88xj6tnl2r4vv6knlag35v25tupa6gey33ru3hyg85k0auk7sfgsas9kj68q7qf0pld3kcquettueyc2p6kw52xdyzga3urvr8s5jptgq23ftphkvf024txw3ll6tuqsp6qnrrg6hvwdzp57jnjxyrtacvan3qe7e5q43z6qwml9yxp5fry0m4g8hhtpzjzvrensnw3ma5s9khppqsx9t8klyprap7mvcs87wg02sapvc4fprdg6wynejkd525hruncr895skvqetkaef3rlh957tpkw58zayfrxtyvgc63qqs47gmyatsvpyvfssam2wt7ra5k330kkml8xp8kpsqpwm6dg5h2jdagmz0hnrs5cyxrrvfq2f5dflk2m458tpq3nydkznsj4wcvpdh4p7em2xfmpv228acv9ns2lm6z8ducet9yatghjap562f2rj42wgqqcnncvzkyr2kn80n3hgas48pm22gvjql6u54ply830y8rr3eqfmwhztn4xa4uar80l96shs9wk9pt5uwscwfatxykqkqj2tnhqz0h4cc0ryesn6u02tdyx9hgvhjkvnlac42f4tmjs3vzzszsrx9p3m78cev4gfkn73krf0zfpttzap3xca9kwl2zezhd39dsa0u0ysy98jq5v329qh94lux6gpeqtz7y7cvk734475awtlkg3s3x2lyfgdphjd58p656385sa5u8qldjupgm2yy5pgqgfy8va2getdepq96xxdw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHc5dUNLdyBBeU0reEFr
            dmd3ekFVTjJ5c0dOTUxkS3RKOHNVb2ROL0dCTnFVWjdlb3p0UQpQTks4YS90UGlt
            THhjT1FTWlBBcmdQVkJpRHk2QTFBUE1oZzIvc0VhcnF3Ci0tLSBwYzB4cmpmTXBo
            RnVXTEZPeUxlUmVwOEZPbHR5UE5HQUtMZm1xSnV4dHZnCvk7egl4PcNZAnZwaxDy
            7oUckCbw3C1XHl22zDsXVv1RZ6xC5mHCSc0nESC70Q4SxG4Tb96O/ho1s2Z4uSWD
            lOY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2a8vlrsl9jm2zdzlhrxd7z7w7fg06rwtzf5pyhxdusps637qmeh7rphj3z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHNoQUYrUSBBbXdtMkRS
            cysvaWxpVUR2YlFxZHpzWnBsMTVkYjh2Q0tvNlBma05hQVpEQgpNbEFQUmJreDZF
            c1ZhSVhSWjJJN0VaM0hVRDkrNk85MVNYaEdMeEE0U1cwCi0tLSBFWjlNeSt5OVVR
            VnJ6Zmw5ZkpKeWNrYkFqQ2JESUpyM2F4blNCOW5GckVFClcxqlNGoVsXzIrhsYAx
            A5RSjQQBkykUjwkk9EChE7yAySUzYdHkQz+2KHX2wJfBf/p2mmsJ6QFmky7V6YiT
            /MA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdjws4vea067rq586qexcsz4k5eqmgh6mnsfld8uwy56dmkwrqhvwnt5e63
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T10:44:02Z"
    mac: ENC[AES256_GCM,data:1eXJH0liwKOyRoy0Cho8Ca8LtNTuNwpvDVFI43FgmYV0/3GJwLWHv1T6eZg79xo+wQ3/y7L/mSY1l+BeRf22fj2YcMh/cDW729Dd47EQqLRK7Jd7eBUvNoAVMay4DP1fT6dQtn0GjKT/gi68CgYiBLYXSUixOXNt2An940a4A4Y=,iv:IKmH9d32wVtgjvP5OAMubl7YG4D0ABTKbY025bK7TBo=,tag:nTwgIvLmnMZjxZP5Cj9XEQ==,type:str]
    version: 3.13.3
