apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://bao.ocf.berkeley.edu"
      path: "cluster-secrets"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"

