apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-cluster-values
  namespace: mariadb
  labels:
    reconcile.fluxcd.io/watch: Enabled
data:
  values.yaml: |
    mariadb:
      rootPasswordSecretKeyRef:
        name: initial-secret
        key: root-password
        generate: false
      storage:
        size: 1Gi
      replicas: 3
      galera:
        enabled: true
    databases:
      - name: ocf
        characterSet: utf8
        collate: utf8_general_ci
        cleanupPolicy: Skip
        requeueInterval: 10h
        retryInterval: 30s

