apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 10m0s
  url: https://coredns.github.io/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  chart:
    spec:
      chart: coredns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: coredns
      version: 1.47.0
  interval: 10m0s
  values:
    prometheus:
      monitor:
        enabled: true
      service:
        enabled: true
    service:
      clusterIP: 10.96.0.10
    serviceAccount:
      create: true
