apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: initial-secret
  namespace: mariadb
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: initial-secret
  dataFrom:
    - extract:
        key: mariadb/initial-secret

