apiVersion: v1
kind: Namespace
metadata:
  name: cilium
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: cilium
spec:
  type: oci
  interval: 10m0s
  url: oci://quay.io/cilium/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  chart:
    spec:
      chart: cilium
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: 1.19.4 # {"$imagepolicy": "flux-system:cilium:tag"}
  interval: 10m0s
  values:
    autoDirectNodeRoutes: true
    bpf:
      masquerade: true
    endpointRoutes:
      enabled: true
    hubble:
      listenAddress: :4244
      relay:
        enabled: true
      tls:
        auto:
          method: cronJob
      ui:
        enabled: true
    ipam:
      mode: kubernetes
      requireIPv4PodCIDR: true
      requireIPv6PodCIDR: true
    ipv4:
      enabled: true
    ipv4NativeRoutingCIDR: 10.244.0.0/16
    ipv6:
      enabled: true
    ipv6NativeRoutingCIDR: 2607:f140:8801:1::/112
    k8s:
      requireIPv4PodCIDR: true
      requireIPv6PodCIDR: true
    k8sServiceHost: dna.ocf.io
    k8sServicePort: "6443"
    kubeProxyReplacement: "true"
    loadBalancer:
      acceleration: native
      mode: hybrid
    routingMode: native
